version: "3.7"

services:

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - .:/var/www/html/
      - ./logs/nginx:/var/log/nginx/

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - .:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log

  mysql_container:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: Password123450
      MYSQL_DATABASE: tpshr-dock

volumes:
   mysql-data:

networks:
  internal:
    driver: bridge